### ISSUE TITLE
Add note on auto-appending for `new`

### ISSUE THREAD

**Issue by Shalmezad** [JorySchossau/mabe-build-tool#1]
Should add a note to `./mbuild new` that it will automatically append the module type (Brain, World, etc) to the provided name.
Or better yet, if the user has the appendage in their module name (ex: `./mbuild new world GreedWorld`), ignore adding the appendage (right now results in `World/GreedWorldWorld`)

**Comment by JorySchossau** [comment]
Good idea. I'll try to test this out for the next release.

**Comment by JorySchossau** [comment]
Fixed in commit 40a3558d0f7405a85fc4b822c39f342464fc550c
